### ISSUE TITLE
React v0.14.0-rc1 peerDependencie

### ISSUE THREAD

**Issue by LukevdPalen** [bebraw/react-pagify#10]
Could you add react 0.14.0-rc1 to the peerDependencies? Unfortunately `react@>=0.11.0 <1.0.0` doesn't cover it.

**Comment by bebraw** [comment]
That sounds interesting. Can you suggest a better pattern? Is there any we can get alpha/beta/rc included? I tried against the [online semver checker](http://semver.npmjs.com/) without any luck. It would suck having to add each alpha/beta/rc separately. I would rather have a range there.

**Comment by bebraw** [comment]
@LukevdPalen I had interesting conversation about the topic. I don't think there's a neat way to solve this through a range. We could add `||` sections to the rule but that would just push the problem to *package.json*.

As far as I can see the simplest solution would be for you to fork the library, tweak/eliminate the range and do `npm i LukevdPalen/react-pagify -S`. Once stable `0.14` gets out, you can drop it. I don't expect any major changes to react-pagify so I expect this could work quite nicely.

**Comment by LukevdPalen** [comment]
No the most beautiful solution but `>=0.13.* <1.0.0 || > 0.14.0-alpha` should at least include the prerelease versions.

**Comment by bebraw** [comment]
`0.8.2` contains the fix. I'm not totally happy about the solution as this needs to be tweaked again in the future but it's the best we can do at the moment.

**Comment by LukevdPalen** [comment]
Thx! :+1:
