### ISSUE TITLE
Dependency not babelizing correctly

### ISSUE THREAD

**Issue by nneal** [bebraw/react-pagify#20]
Forgive me if this a browserify issues and not one with `react-pagify`!

We want to use `react-pagify` in production but unfortunately it currently breaks Safari because the `const`s in segmentize/intersect are not babelizing to `var` correctly. We have plenty of other NPM modules included in our application, and all seem to be babelized to es5 correctly. That's why i'm wondering if it's some kind of issue with this module

Code in question:

```
const intersect = require('intersect');
const uniq = require('uniq');

module.exports = function (o) {
  const page = o.page;
  const pages = o.pages;
  const leftSidePages = o.sidePages ?
    range(Math.max(page - o.sidePages, 0), page) :
    [page - 1];
  const rightSidePages = o.sidePages ?
```

browserify settings in application.rb

`config.browserify_rails.commandline_options = "-t [ babelify --presets [ es2015 react ] ]"`

**Comment by nneal** [comment]
Nvm, updated to latest version which seemed to fix issues

**Comment by bebraw** [comment]
Great to hear you got it sorted out!

There was a temporary glitch indeed. That was sorted out at the API rewrite. :+1:
