### ISSUE TITLE
Issue with 'lodash/merge'

### ISSUE THREAD

**Issue by Joramt** [bebraw/react-pagify#22]
Hi,
I've been looking to use react-pagify for one of our company's project. After installing module depencies appropriately, it appears that react-pagify cannot find the lodash/merge modules, thus blocking the project compilation. After looking quickly into your code, i found that commit might be responsible for it ( 3088cdee756f5213b7cd16524156ee1ece9c06bb ).
Thanks for the time spent investigating this issue.

**Comment by bebraw** [comment]
`lodash/merge` is something lodash 4 specific. Are you on lodash 3?

We could perhaps refactor the code so that you could inject `merge`. This would break the dependency.

**Comment by bebraw** [comment]
Ah, I see it now... It's that `external` definition causing the issues.

**Comment by bebraw** [comment]
@Joramt I fixed the `external` issue at `2.0.3`. Let me know if there are any further issues.
