### ISSUE TITLE
Going to last page

### ISSUE THREAD

**Issue by Ezekiah** [bebraw/react-pagify#23]
Hello,

Can i know how I can go to the last page of the pagination with some code ?
In the version 0.9 it was quite easy but now that I updated I dont know how to do that.

**Comment by bebraw** [comment]
You will have to go through the `segments` prop. Example:

```javascript
  segments={{
    centerPage: [currentPage]
  }}
```

So in this case you would need to adjust that `currentPage` variable through your state management mechanism.

Would it help if I implemented this in the demo?

**Comment by Ezekiah** [comment]
Oh yes I would appreciate this.

**Comment by bebraw** [comment]
There's a little demo now. I hope that helps. :+1:

**Comment by Ezekiah** [comment]
Thanks :+1:
