### ISSUE TITLE
Suggestion for increased usability

### ISSUE THREAD

**Issue by OracPrime** [bebraw/react-pagify#24]
Hi,

** Proposal to either provide a new example, modify this component, or set up a new component using this; I'm new to this, so don't really know! **

I've been using this in my project.  I'm a bit of a JS newbie, but I found the current structure a bit "heavy".  In particular I find that I need a consistent paging style for multiple tables, but don't want the overhead of the react-pagify syntax around it every time.   Now I may have missed an easier way, but the approach I've adopted is to wrap your component so that it can take a generic inner table.  So for example I have an ActivitiesComponent to display a pagified table of activities, and my render is as simple as:

    render() {
        return ( <SwPager data={this.state.acts} innerTable={new ActivitiesTable() } /> );
    }

where this.state.acts is my data obtained from the server.  I feel this level of simplicity for adding new instances is a major ease-of-use factor.

inner table is your table-rendering component of choice with a wrapper that supports a setData method, and SwPager is a generic wrapper around react-pagify, based very much on your sample here using segmentize; the difference being that the render function contains a 
    {this.props.innerTable.render()}
as its main content.

It just seems that enabling a pagified table to be a one-line per instance rather than the 150-ish lines in your demo can only be a good thing?

Regards

David.

**Comment by bebraw** [comment]
Hi David,

Thanks for your comment. The point of the new API was to provide building blocks for people so they can build their own paginators. I agree it's very verbose by default. In fact, the idea is that people build a custom component wrapping all that verbosity. So you could easily end up with `SwPager` or a similar component fitting the purposes of your project.

I think I'll simplify the demo to illustrate this point. Thanks again. :+1:

**Comment by bebraw** [comment]
I expanded the demo so that there's a component example. That simplifies the paginator interface a lot.

**Comment by OracPrime** [comment]
Thanks - I think your DemoPaginator is a good step in the right direction.  Personally I would still take it further and encapsulate all of the paging logic - e.g. moving the onSelect method inside (after all, how often is that likely to change between instances).  There are also two major use cases, I would suggest; one as per your demo where you use map to extract the elements and render them, but the more likely one is that someone already has a component - probably a table component (in my case reactabular) - which expects an array of data to start with.  My approach allow me to define my ActivitiesTable in such a way that it is reusable with or without pagination with no code change.

I can't help feeling that there should be a way of doing it without the setData call on ActivitiesTable and somehow making it work via props, but my js skills aren't yet good enough to work out how to do that.  At the moment my swPager render method is like this

   render() {
        const data = this.props.data || [];
        const pagination = this.state.pagination || {};
        const paginated = paginate(data, pagination);
        const pages = Math.ceil(this.props.data.length / Math.max(
            isNaN(pagination.perPage) ? 1 : pagination.perPage, 1)
        );
**        this.props.innerTable.setData(paginated.data);**
        return (
            <div>
**                {this.props.innerTable.render() }**
                <div>

                    <Paginator.Context className="pagify-pagination"
                        segments={segmentize({
...... etc.

I can't help feeling there must be a way of passing the inner table in uninstantiated and then providing it with the necessary props.  So effectively

return (  <InnerTable data={paginated.data} /> .... etc)

but with InnerTable being an instance of a class that is passed in as an argument.

Anyway, thanks for your fast response and improvement.

David

**Comment by bebraw** [comment]
When it comes to logic, there's no one right way. Pushing it to a paginator can make sense in some cases, but it can also be useful to keep it outside. In the demo the paginators share the same state for instance so it needs to be managed just this way. If you implemented a state management solution such as Redux, you would push logic and state there.

In your case `ActivitiesTable` can definitely encapsulate both table and paginator(s). That's one nice way to approach it. Again, you could push the logic and state elsewhere and keep the view related components simple.

It could be fun to write an expanded example to show how Redux, reactabular, and react-pagify go neatly together. I've done something like this and it works quite well after you get the wiring done. It's a lot of code for sure but it's flexible as well.
