### ISSUE TITLE
npm 2 and windows => ko 

### ISSUE THREAD

**Issue by FredericHeem** [bebraw/react-pagify#25]
react-pagify doesn't seem work on Window, the `dist-modules` does not exist on this platform but is present on mac/linux.

**Comment by bebraw** [comment]
That sounds weird. Perhaps it's something npm related? Why would the directory be missing?

I gave it a go myself and it definitely appears on mac. We just need to understand why it fails on Windows.

**Comment by FredericHeem** [comment]
The npm version is 2.15.1, I'll update it to find out if it is npm related.

**Comment by bebraw** [comment]
Cool. I'm on npm 3 so maybe that's it.

It's clear the files are getting uploaded. I just don't understand why the Windows build is missing them.

**Comment by FredericHeem** [comment]
It's definitely linked to npm,  no issue with npm 3.

**Comment by bebraw** [comment]
Ok. Maybe there's a related issue at the npm issue tracker. If not, time to create one.

Note that I published the package on npm 3 so maybe that could explain something.

**Comment by bebraw** [comment]
@FredericHeem What do you want to do with this? Maybe just document the issue? There's not much we can do on the package side. 😞

**Comment by bebraw** [comment]
@FredericHeem Can you give another look? Maybe something has changed.

**Comment by bebraw** [comment]
Let’s close this. npm 3 is starting to be mainstream
