### ISSUE TITLE
React 15.2: Warning: Unknown prop `page` on <div> tag.

### ISSUE THREAD

**Issue by foxhound87** [bebraw/react-pagify#26]
Please remove the following warning on react 15.2:

Warning: Unknown prop `page` on `<div>` tag.
Remove this prop from the element. 
For details, see https://fb.me/react-unknown-prop

**Comment by bebraw** [comment]
Fixed in `2.1.0`. Thanks for the report.

**Comment by foxhound87** [comment]
thanks!
