### ISSUE TITLE
Disable next and previous buttons

### ISSUE THREAD

**Issue by hellectronic** [bebraw/react-pagify#27]
Hello,
just wanted to know if there is a reason why the next and previous buttons are not disabled when first or last page is selected?

**Comment by bebraw** [comment]
No particular reason. The component itself doesn't deal with concerns like this, but if you want you could [PR a change to `DemoPaginator`](https://github.com/bebraw/react-pagify/blob/master/demo/DemoPaginator.jsx).

I'll most likely add the check myself later on. Just something like `className={!pagination.page && 'disabled'}` etc.
