### ISSUE TITLE
Segmentizer algorithm

### ISSUE THREAD

**Issue by rowbare** [bebraw/react-pagify#6]
When dealing with a relatively small number of pages, the segmentizer gets confused in the middle range. For example with 11 pages and a before and after of 3

Previous 1 2 3 … 6 7 8…9 10 11 Next

Previous 1 2 3 … 11 7 8 9 10 Next

bob

**Comment by bebraw** [comment]
@rowbare Thanks! `uniq` didn't behave as I expected. Now it should sort pages correctly. A lot of little corner cases like this.
