### ISSUE TITLE
Pagination when there are 7 pages: 3 4 5 ... 5 6 7

### ISSUE THREAD

**Issue by nicoecheza** [bebraw/react-pagify#9]
Just that. 
1. Check the example http://bebraw.github.io/react-pagify/
2. Change Per page to 1500.
3. The paginator goes crazy and shows this: Previous 1 2 3 4 **5** … **5** 6 7 Next

:dancer:

**Comment by bebraw** [comment]
Thanks a lot! It was missing some merging math. Fixed in `0.8.1`.

**Comment by nicoecheza** [comment]
Nice. Thanks :D
